### ISSUE TITLE
Path module error

### ISSUE THREAD

**Issue by romuleald** [at0g/nunjucks-loader#19]
Hello,

I'm using the nunjucks-loader and I've got this strange error on the path of node_module (the second part)

    ERROR in ./Resources/public/templates/_briefList.nunjucks.nunj
    Module not found: Error: Cannot resolve 'file' or 'directory' .\Resources\public\js\src\vendors\nunjucks.js/browser/nunjucks-slim in .\Resources\public\templates
    @ ./Resources/public/templates/_briefList.nunjucks.nunj 1:15-73

    ERROR in ./Resources/public/templates/_briefList.nunjucks.nunj
    Module not found: Error: Cannot resolve module 'D:devpmplanningserver
    ode_modules
    untime-shim' in .\Resources\public\templates
    @ ./Resources/public/templates/_briefList.nunjucks.nunj 13:11-89

Is it a problem because of windows?

    node 4.1.1
    Webpack 1.12.2
    nunjucks 2.1.0
    nunjucks-loader 2.2.1

Thanks for helping me understanding that!

**Comment by oh-ren** [comment]
Just trying to get started here with Nunjucks <> webpack, so far not that successful.. ;)

I pinned down this issue, but now getting an `obj is undefined` error in my browser console from my bundle:
```javascript
	module.exports = function (nunjucks, env, obj, dependencies){

	    var oldRoot = obj.root;
````
Not sure about that yet, but regarding this issue, the culprit is to be found here: https://github.com/at0g/nunjucks-loader/blob/master/index.js#L126
This returns a path with backward slashes on Windows, which will be evaluated again by JS (webpack?) later.. thus the slashes then being interpreted as escape characters..
A dirty hack is appending `.replace(/\\/g, '\\\\')`to the `path.resolve` statement.
Another way could be wrapping the `path.resolve` in a `slash` function call.

But.. (being a newbie regarding Node) isn't the use of `slash` futile here anyway? Doesn't `path.resolve` create a Windows path with backward slashed anyway? (+ I don't really get the advantage of using `slash`, as it just might as well can't render the path in a forward-slashed version, so you can't rely on the output?)

Cheers

**Comment by at0g** [comment]
Hello - sorry about the slow reply - sounds as though it's a windows bug.

Can you try the 2.1.0 version and let me know if the issue persists?

`npm install nunjucks-loader@2.1.0`

I suspect your issue might have been introduced with #13

**Comment by oh-ren** [comment]
@at0g Thanks, yes that fixes the issue! (Although still the `shim` require path needs patching.) 

(So, figured out I need the `changelog` package to keep track of the versions/changelog in a decent fashion.. ;))

**Comment by at0g** [comment]
Hello @romuleald / @oh-ren 

I've pushed a new branch up here that will hopefully fix the issue:

https://github.com/at0g/nunjucks-loader/tree/hotfix/19-win-paths

@romuleald - in your original error:
```
Module not found: Error: Cannot resolve 'file' or 'directory' .\Resources\public\js\src\vendors\nunjucks.js/browser/nunjucks-slim in .\Resources\public\templates
```

The path after nunjucks.js is wrong - this is fixed in the branch above. It may still be be an issue, as it looks as your vendor nunjucks.js is a file rather than a directory. 

@oh-ren - I think (maybe) the shim path is fixed now - I will try and get a windows VM sorted to test with.

**Comment by wengqi** [comment]
I also met the same problem in windows system. I use nunjucks-loader@2.0.3 to resolve this issue. Other version can't work.

**Comment by oh-ren** [comment]
Hi,

Sorry for the late response.

But I'm at it again.. On Windows.. The changes in index.js in the hotfix branch didn't seem to help in regard to my issue.
I'm still on / went back to 2.1.0 with my own `shim` require slash fix (which isn't fixed in the hotfix branch).

**Comment by at0g** [comment]
@oh-ren - can you share your shim require fix with me as a diff or pr?

**Comment by oh-ren** [comment]
Seems this can be closed thanks to the PR's from @opterion :+1:

**Comment by at0g** [comment]
Thanks @opterion + @oh-ren
